version: "3.3"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      MSSQL_PID: "developer"
      SA_PASSWORD: "toor!123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    expose:
      - "1433"